### ISSUE TITLE
Adding fade in / out as an option

### ISSUE THREAD

**Issue by marqmarti** [rfoel/bulma-toast#11]
Hi, excellent contribution. Perhaps you could add a **fade in** and **fade out** option? The vast majority of toasts I've seen around the web use the fade behavior.

**Comment by rfoel** [comment]
Yeah I've seen that. Maybe not just fade-in/fade-out, but an option to add animations? Like bounce, slide, etc...? I'll work on it.

**Comment by rfoel** [comment]
I added support for [Animate.css](https://daneden.github.io/animate.css/). [See here](https://github.com/rfoel/bulma-toast#animate).

**Comment by marqmarti** [comment]
Awesome!!
