### ISSUE TITLE
Ability set a DOM node for the message

### ISSUE THREAD

**Issue by peterbe** [rfoel/bulma-toast#13]
E.g.

```javascript
setTimeout(() => {

  const elm = document.createElement('a')
  elm.text = "Click This"
  elm.href = "http://url.example.com"

  toast({
    message: elm,
    type: "is-info",
    dismissible: true,
    duration: 20000
  });
}, 2000);
```

It could be something like:

```javascript
// UNTESTED

if (typeof this.message === 'string') {
  this.element.insertAdjacentText("beforeend", this.message);
} else {
  this.element.appendChild(this.message);
}
```

**Comment by rfoel** [comment]
I think it could be done this way. I will think about it and release it soon.

**Comment by rfoel** [comment]
@peterbe Do you think the user should also be able to set a template string like 
```js
const message = `<h1>${name}</h1>`
```
or even a string?
```js
const message = "<h1>Hello There</h1>"
```
I'm wondering if I should implement that.

**Comment by peterbe** [comment]
No I don't think so. That feels fragile and then it's not possible to attach a DOM event listener if it's injected as a string (e.g. `innerHTML`).

**Comment by rfoel** [comment]
Well, that's true. I used your solution and instead of using insertAdjacentText I'm using insertAdjacentHTML.

```js
    if (typeof this.message === "string") {
      this.element.insertAdjacentHTML("beforeend", this.message);
    } else {
      this.element.appendChild(this.message);
    }
```

**Comment by peterbe** [comment]
I wish there was a way, in GitHub or something, to subscribe to a git commit and be notified when that git commit becomes part of a tag/release or something that is published on npmjs.
