### ISSUE TITLE
Why does the notification/toast looks like this? 

### ISSUE THREAD

**Issue by construelabs** [rfoel/bulma-toast#188]
<img width="328" alt="Screen Shot 2021-07-20 at 6 08 53 PM" src="https://user-images.githubusercontent.com/57211610/126326383-dfbd8ea1-e441-42db-98ac-f5a2e182cea7.png">

The close/delete button seems to be at the wrong position. thanks

**Comment by rfoel** [comment]
Probably mismatch of Bulma version. This package uses `v0.7.1` and apparently it is already on `v0.9.3`. I haven't use Bulma myself in years now, I just keep this plugin updated.

**Comment by construelabs** [comment]
ok np, I think I can add some simple css to fix this. thanks
