### ISSUE TITLE
PR #202 not merged properly

### ISSUE THREAD

**Issue by yatharth** [rfoel/bulma-toast#204]
I don’t think #202 was merged properly. The changes to `src/index.js` for examples are not to be found. I think you created 188058a to squash my three commits, and meant to apply  4f08fdf on top of that, but 188058a is nowhere on main.

**Comment by rfoel** [comment]
Oh sorry, I had to juggle with your PR because I don't write package version manually, I have a GitHub Action that bumps it once it is pushed to main. I may have deleted your changes. Now I think it's ok.

**Comment by yatharth** [comment]
Ah, gotcha. Out of curiosity, what is your workflow for that: you must be indicating somewhere at least whether the bump patch number or minor number or major number at least before you push, right?
