### ISSUE TITLE
creating a new instance of the toast class causes issues in SSR environments :(

### ISSUE THREAD

**Issue by NullVoxPopuli** [rfoel/bulma-toast#3]
Just upgraded to 1.0.0 from 0.1.0
The issue is that the default export in 1.0.0 is https://github.com/rfoel/bulma-toast/blob/master/src/js/index.js#L58 trying to access the `document` when bulma-toast is imported.

but in 0.1.0, just an function is exported: https://github.com/rfoel/bulma-toast/blob/0.1.0/src/extension.js#L7
so it's not evaluated until invocation time, allowing it to work in SSR environments. :-\

(for now, I'm downgrading back to 0.1.0 :-\\ )

Ran in to this issue: https://github.com/ember-fastboot/ember-cli-fastboot/issues/74 (for reference)

**Comment by rfoel** [comment]
I will probably revert it. I will try to keep it simple. Thanks for pointing it out.

**Comment by rfoel** [comment]
@NullVoxPopuli please check out the new version.

**Comment by NullVoxPopuli** [comment]
outside of server-side rendering, when I just swapped out the version in my package.json, I noticed this: 
![image](https://user-images.githubusercontent.com/199018/43708846-6919288e-9939-11e8-8b2b-0f137de30778.png)

my options.position is `is-right`, when it should have been `top-right`, and I see now that the documentation is updated to use the new values. So, I think we're good! (I changed the value to one of the allowed values mentioned in the readme, and things behave as expected)

Thanks @rfoel !!! <3

**Comment by NullVoxPopuli** [comment]
also, I love this:
![image](https://user-images.githubusercontent.com/199018/43709068-e5973450-9939-11e8-922a-2f1c6a64d826.png)

https://github.com/NullVoxPopuli/react-parcel-playground
![image](https://user-images.githubusercontent.com/199018/43709282-649fccc6-993a-11e8-81f3-0a5d0d81717f.png)

<3 Prequel Memes
