### ISSUE TITLE
"Document is not defined" every time I refresh in the same page

### ISSUE THREAD

**Issue by kensixx** [rfoel/bulma-toast#33]
![image](https://user-images.githubusercontent.com/24205790/67452969-9e4dd780-f657-11e9-8369-7fce2b8f9ed5.png)

I'm just wondering why I'm getting this every after I refresh at the same page that I'm working on.
Or, when nuxt.js hot-reloads the page whenever I change some code.

This is my current <script> in my page:

```
<script>
import { toast } from 'bulma-toast'

export default {
  methods: {
  async onUpload() {
    try {
      // ... send to axios and save to browser

      toast({
        message: 'Success! Your file is now saved.',
        position: 'top-center',
        type: 'is-success',
        dismissible: true,
        pauseOnHover: true,
        animate: { in: 'bounceInDown', out: 'bounceOutUp' }
      })

      console.log(response)
    } catch (e) {
      console.error(e)
      // TODO: create a variable for this "toast.message."
      toast({
        message: 'Something went wrong...',
        position: 'top-center',
        type: 'is-danger',
        dismissible: true,
        pauseOnHover: true,
        animate: { in: 'bounceInDown', out: 'bounceOutUp' }
      })
    } finally {
      this.isLoading = false
    }
}
</script>
```

**Comment by daytonmills** [comment]
I'm assuming you're using next.js like I am right? Due to the server side nature of next.js I because this is because it's importing before the document exists.

A workaround I found was to instead require the module later on in my code in a function that is called after the page is already rendered.

**Comment by MarcusMann** [comment]
@daytonmills can you show a example? Thanks

**Comment by rfoel** [comment]
Try to require it inside OnUpload method.
```
async onUpload() {
  const { toast } = require('bulma-toast')
  ...
```

**Comment by baocancode** [comment]
`const { toast } = require('bulma-toast')` works, but will lose the benefit of Typescript. Quick look at the code, I think it can be fixed by not assigning `let doc = document` at the beginning. Something like this:

```
let doc

export function toast(params) {
  if (!doc) {
    doc = document
  }
}
```

**Comment by tonprince** [comment]
hi,
I have the same issue when using bulma-toast with Sveltekit.

ReferenceError: document is not defined
