### ISSUE TITLE
Demo link no longer works

### ISSUE THREAD

**Issue by caffeinatedMike** [rfoel/bulma-toast#36]
As the title states, the demo site doesn't seem to be active anymore. Any chance it can be updated?

**Comment by rfoel** [comment]
The demo link is [](https://rfoel.github.io/bulma-toast/), it is working.

**Comment by rfoel** [comment]
This is the demo link [https://rfoel.github.io/bulma-toast/](https://rfoel.github.io/bulma-toast/)
