### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by B-PRAVEEN** [rfoel/bulma-toast#48]
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
Suddenly this error came after installing the module in our new project.

**Comment by rfoel** [comment]
@B-PRAVEEN can you make a example repo?

**Comment by rfoel** [comment]
@B-PRAVEEN can you make an example repo?

**Comment by croumegous** [comment]
I got the same error when I tried to use :  
`toast({
              message: error,
              type: 'is-warning',
            });`  
But `error` was actually an array and not a string.  
(So in my cas I just needed to use error.toString() )
