### ISSUE TITLE
No SSR support

### ISSUE THREAD

**Issue by kkarkos** [rfoel/bulma-toast#52]
I used "bulma-toast" on a gatsby project where the build would fail with ```WebpackError: ReferenceError: document is not defined``` . Maybe add some some if(window.document...) for the plugin. Had to remove it, but was working great! Good work.

**Comment by rfoel** [comment]
That probably would do. Mind working on a PR?

**Comment by kkarkos** [comment]
I actually found another workaround using: https://github.com/jamiebuilds/react-loadable.

**Comment by rfoel** [comment]
Fixed in the last PR
