### ISSUE TITLE
Allow overriding position

### ISSUE THREAD

**Issue by sourav-tinydojo** [rfoel/bulma-toast#54]
Please allow passing the position value. The the current value anchors the initial positions to 0.

**Comment by rfoel** [comment]
Can you give an example?

**Comment by ykyuen** [comment]
I guess @sourav-tinydojo is talking about the position definition in the [source file](https://github.com/rfoel/bulma-toast/blob/6c5e1bf444b706130776aea395082ad126425827/src/index.js#L18). ex

```
'bottom-right': 'right:0;bottom:0;text-align:right;align-items:flex-end;',
```
In my case i my react application has a fixed bottom bar and i would like to override the `bottom` css above such that i could offset its position avoiding the toast div overlapped on the fixed bottom bar.

Here is my code change of adding 4 new offset options
