### ISSUE TITLE
Toast should not destroy the container while it has other toasts.

### ISSUE THREAD

**Issue by leqwasd** [rfoel/bulma-toast#55]
At the moment, when the toast is destroyed, it destroys the parent. That parent could have other toasts within it. It deletes those toast nodes aswell. You should check, if the parent has any nodes in it, if it hasn't, then delete it.

**Comment by leqwasd** [comment]
https://github.com/rfoel/bulma-toast/pull/56

**Comment by rfoel** [comment]
Thanks for the PR, merged.
