### ISSUE TITLE
SyntaxError: Unexpected token '<' in console?

### ISSUE THREAD

**Issue by ppedrazzi** [rfoel/bulma-toast#57]
Really enjoying bulma-toast and have it working with svelte, bulma, and animate.css quite well.  Super nice and easy.

I do see 'SyntaxError: Unexpected token '<'' in the console pointing to 'anonymous function' at bulma-toast-min-js-1.  Have you see this before?

**Comment by rfoel** [comment]
Could you create a sandbox with this case isolated? I haven't really used this package in years, but I keep maintaining it.

**Comment by ppedrazzi** [comment]
Thanks for the reply - I'll see what I can do. I'm sure the issue is on

my side - perhaps I'm loading it to much (ie. importing on multiple
files vs once for the app)....
